### ISSUE TITLE
config.yamlの設定値が固有名詞になっています。

### ISSUE THREAD

**Issue by mastada** [yahoojapan/hosted-danger#6]
## 概要
https://github.com/yahoojapan/hosted-danger/blob/master/spec/config.yaml#L17-L25
```
secrets:
  - name: sd_user_token_cd
    env: SD_USER_TOKEN_CD
  - name: sd_user_token_next
    env: SD_USER_TOKEN_NEXT
  - name: dragon_access_key
    env: DRAGON_ACCESS_KEY
  - name: dragon_secret_access_key
    env: DRAGON_SECRET_ACCESS_KEY
```

こちらの設定値ですが、デフォルトで記載するサンプル値としては不親切だと感じました。

## 提案内容
secretsには任意の名称/値を設定可能かと思いますので、そうとわかる名称にしていただけるとよりわかりやすいかと思います。（例えば以下のような）
```
secrets:
  - name: my_secret_cd
    env: MY_SECRET_CD
```

合わせて、https://github.com/yahoojapan/hosted-danger/blob/master/docs/launch_server.md にもsecretsに関する記載があると良いなと思いました。
